kind: pipeline
name: default

steps:

  - name: deploy-ssh
    image: appleboy/drone-ssh
    enviroment:
        TEST_DATA:
          from_secret: test_data
    settings:
      host:
        - 100.90.71.128
      username: nax
      password:
        from_secret: ssh_password
      port: 22
      command_timeout: 2m
      envs:
        - [ TEST_DATA ]
      script:
        - echo $TEST_DATA
        - echo ${TEST_DATA}
        - echo $${TEST_DATA}