kind: pipeline
name: default

steps:
  - name: test
    image: python
    commands:
      - python -m pip install poetry
      - python -m poetry install
      - python -m poetry run python -m pytest

  - name: docker
    image: plugins/docker
    settings:
      insecure: true
      repo: 100.90.71.128:8082/nax/days_count
      registry: 100.90.71.128:8082
      username:
        from_secret: nexus_username
      password:
        from_secret: nexus_password

  - name: deploy-ssh
    image: appleboy/drone-ssh
    settings:
      host:
        - 100.90.71.128
      username: nax
      password:
        from_secret: ssh_password
      port: 22
      command_timeout: 2m
      script:
        - echo "Hello World"