kind: pipeline
name: default

steps:

  - name: deploy-ssh
    image: appleboy/drone-ssh
    settings:
      host:
        - 100.90.71.128
      username: nax
      password:
        from_secret: ssh_password
      port: 22
      command_timeout: 2m
      envs:
        - test_data
      script:
        - export TEST_DATA=$TEST_DATA
        - echo ${TEST_DATA}