kind: pipeline
name: default

steps:
  - name: deploy-ssh
    image: appleboy/drone-ssh
    environment:
      NEXUS_USER:
        from_secret: nexus_username
      NEXUS_PASSWORD:
        from_secret: nexus_password
    settings:
      host:
        - 100.90.71.128
      username: nax
      password:
        from_secret: ssh_password
      port: 22
      command_timeout: 2m
      envs: [ NEXUS_USER, NEXUS_PASSWORD ]
      script:
        - echo $NEXUS_USER
        - pwd
        - whoami
        - where docker
        - where docker-compose
        - docker login -u $NEXUS_USER -p $NEXUS_PASSWORD 100.90.71.128:8082